mex linscan_aqd_knn_mex.cc linscan_aqd.cc -Iinclude CXXFLAGS="\$CXXFLAGS ...
     -Wall" LDFLAGS="\$LDFLAGS";
mex linscan_hamm_knn_mex.cc linscan_hamm.cc -Iinclude CXXFLAGS="\$CXXFLAGS ...
     -Wall" LDFLAGS="\$LDFLAGS";
